blank_issues_enabled: false
contact_links:
  - name: @chainbuilders
    url: https://t.me/chainbuilders
    about: Opensource blockchain developers telegram group
  - name: @stabilitydao
    url: https://t.me/stabilitydao
    about: Stability community
